<div class="modal fade" id="vpnModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo ('Close'); ?></span></button>
                <h4 class="modal-title" id="myModalLabel">
                    <?php
                        /// TRANSLATORS: header/title context
                        echo _('Disconnect from VPN');
                    ?>
                </h4>
            </div>
            <div class="modal-body">
                <?php echo _('By disconnecting from the VPN, your data will no longer be encrypted. Are you sure this is what you want to do?'); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('No'); ?></button>
                <button type="button" class="toggle-vpn btn btn-primary"><?php echo _('Yes'); ?></button>
            </div>
        </div>
    </div>
</div>
