#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 1 ]
then
	/nak/scripts/reset_uplink_wifi.sh
elif [ "$SEEN" -gt 5 ]
then
	/nak/scripts/reset.sh
fi
