<div id="torTile" class="tile <?php if ($this->_params['tor_status'] == '100') echo "connected"; ?>">
    <div id="TorStatus">
        <?php if ($this->_params['tor_status'] == '100'): ?>
            <h3>You are connected to Tor</h3>
        <?php else: ?>
            <h3>Connecting to Tor</h3>
        <?php endif; ?>
    </div>
    <div class="progress">
        <div id="torprogressbar" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <?= $this->_params['tor_status']?>%">
            <span class="sr-only">10% Complete (success)</span>
        </div>
    </div>
    <p>The Tor network can be used to circumvent censorship. Tor will send your data through different countries to bypass filtering.</p>
    <a class="btn btn-primary btn-lg btn-block btn-danger" data-toggle="modal" data-target="#tordcModal">Disconnect from Tor</a>
</div>
