<div class="modal fade" id="tordcModal" tabindex="-1" role="dialog" aria-labelledby="myTordcLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Disconnect from Tor</h4>
            </div>
            <div class="modal-body">
                <p>By disconnecting from the Tor network, your data will no longer be anonymized. Are you sure this is what you want to do?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="toggle-tor btn btn-primary" data-dismiss="modal">Yes</button>
            </div>
        </div>
    </div>
</div>
