<div class="modal fade" id="wanModal" tabindex="-1" role="dialog" aria-labelledby="myWanLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only"><?php /* TRANSLATORS: as in: close the dialog */ echo _('Close'); ?></span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><?php echo /* TRANSLATORS: window header */ _('Connecting'); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo _('Connecting...'); ?></p>
                <center><img src="/img/load.gif" /><br><br></center>
            </div>
        </div>
    </div>
</div>
