<div class="modal fade" id="wifiModal" tabindex="-1" role="dialog" aria-labelledby="myWifiLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo _('Close'); ?></span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo _('Change Network:'); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo _('Choose a new wireless network to connect to with the NetAidKit and enter the password if any:');?></p>
                <?php echo _('<h3>Select a wireless network:</h3>'); ?>
		<div style="float: right">
	                <button id="wifi-refresh" type="button" class="btn btn-primary btn-default"><?php echo _('Refresh'); ?></button>
		</div>
                <form id="wan-form" action="/admin/wan" method="POST">
                    <div id="wifi-list"></div>
                    <div class="login-form">
                        <div class="form-group">
                            <input name="key" type="password" class="form-control login-field" value="" placeholder="<?php echo _('Wifi Password'); ?>" id="login-pass" />
                            <label class="login-field-icon fui-lock" for="login-pass"></label>
                        </div>
                        <a onclick="$('#wifiModal').modal('hide');" id="wan-submit" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#wanModal"><?php echo _('Connect'); ?></a>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cancel'); ?></button>
            </div>
        </div>
    </div>
</div>

<?php include ('connecting.phtml'); ?>
