<?php include ('admin/js/admin.pjs'); ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <h3>Welcome!</h3>
        <?php $this->_displayMessages(); ?>
        <p>The NetAidKit is currently connected to the following wireless network:</p>
        <?php include('admin/tiles/wireless.phtml'); ?>
        <?php include('admin/tiles/internet.phtml'); ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <?php include('admin/tiles/tor.phtml'); ?>
        <?php include('admin/tiles/vpn.phtml'); ?>
    </div>
</div>
