<?php include ('notify/js/notify.pjs'); ?>
<?php include ('admin/js/admin.pjs'); ?>

<?php include ('admin/menu.phtml'); ?>
<?php include ('notify/notify.phtml'); ?>
<?php include ('update/tiles/notification.phtml'); ?>

<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <?php echo _('<h3>Welcome!</h3>'); ?>
        <?php $this->_displayMessages('setup'); ?>
        <p><?php echo _('The NetAidKit is currently connected to the following wireless network:'); ?></p>
        <?php include('admin/tiles/wireless.phtml'); ?>
        <?php include('admin/tiles/internet.phtml'); ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <?php include('admin/tiles/tor.phtml'); ?>
        <?php include('admin/tiles/vpn.phtml'); ?>
    </div>
</div>
