<html>
	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Starting</title>
        <link rel="icon" type="image/png" href="/img/favicon.png">		
		<meta http-equiv="refresh" content="15">
        <link href="/dist/css/flat-ui.css" rel="stylesheet">
		<link href="/dist/css/style.css" rel="stylesheet">
	</head>
	<div class="row">
		<div class="col-xs-12 col-md-6">
			<center>
				<br>
				<h3>Starting</h3>
				<p>The device is busy starting up...</p>
				<br><br><img src="/img/load.gif" /><br><br>
			</center>
		</div>    
	</div>
</html>
