<?php include 'admin/menu.phtml'; ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <h3>Tor</h3>
        <p>This is the basic Tor logfile (<a href="/logs/download_tor">click to download</a>).</p>
        <?php include 'logs/tiles/tor.phtml'; ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <h3>OpenVPN</h3>
        <p>This is the basic OpenVPN logfile (<a href="/logs/download_vpn">click to download</a>).</p>
        <?php include 'logs/tiles/openvpn.phtml'; ?>
    </div>
</div>
