<?php include 'settings/js/settings.pjs'; ?>

<?php include 'admin/menu.phtml'; ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <h3>Wireless</h3>
        <p>Here you can manage the NetAidKit basic wireless configuration settings.</p>
        <?php $this->_displayMessages(); ?>
        <?php include ('settings/tiles/wireless.phtml'); ?>
    </div>
</div>
