<?php include 'settings/js/settings.pjs'; ?>

<?php include 'admin/menu.phtml'; ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <h3>Wireless</h3>
        <p>Here you can manage the NetAidKit basic wireless configuration settings.</p>
        <?php $this->_displayMessages('ap'); ?>
        <?php include 'settings/tiles/wireless.phtml'; ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <h3>Password</h3>
        <p>Here you can change the NetAidKit admin login password.</p>
        <?php $this->_displayMessages('pwd'); ?>
        <?php include 'settings/tiles/password.phtml'; ?>
    </div>
</div>
