<?php include ('setup_lang/js/setup_lang.pjs'); ?>

<div class="container container-table">
    <div class="row vertical-center-row">
        <div class="text-center col-md-4 col-md-offset-4">
            <img src="/img/logo/logo-nak-square.png">
        </div>
        <div class="text-center col-md-4 col-md-offset-4">
            <p>
                Select language<br/>
                Selecteer taal<br/>
                Wybierz język<br/>
            </p>
        </div>
        <div class="text-center col-md-4 col-md-offset-4">
            <?php include ('setup_lang/tiles/setup_lang.phtml'); ?>
        </div>
    </div>
</div>
