<script type="text/javascript">
$(document).ready(function() {
    $('#wan-submit').click(function(event) {
      $.ajax({
        type: "POST",
        url: "/setup/wan",
        data: $('form#wan-form').serialize(),
        success: function(data) {
          if (data == 'SUCCESS') {
            window.location.href = '/admin/index';
          } else {
            alert(data);
          }
        },
      });
      event.preventDefault();
    });
});
</script>  

       <div class="row">
            <div class="col-xs-12 col-md-6">
                  <img src="/img/logo/logo-nak-square.png">
                  <h3>Connect</h3>
                  <p>The NetAidKit is currently not connected to the Internet.</p>
                  <p>To connect, choose a wireless network on the right.</p>
                  <p>Enter a password if the network requires it.</p>
                  <p>Click on the Connect button.</p>
                  <p>Alternatively, you can connect by plugging a network cable into the WAN port</p>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="modal fade" id="wanModal" tabindex="-1" role="dialog" aria-labelledby="myWanLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                          <h4 class="modal-title" id="myModalLabel">Connecting</h4>
                        </div>
                        <div class="modal-body">
                          <p>Connecting...</p>
                          <img src="/img/load.gif" />
                        </div>
                      </div>
                    </div>
                </div>
                  <div class="tile">
                        <h3>Select a wireless network:</h3>
                        <form action="/setup/wan" method="POST" id="wan-form">
                            <?php $i=1; foreach ($this->_params['wifi_list'] as $ssid): ?>
                            <label class="radio"><input type="radio" name="ssid" id="optionsRadios<?= $i++; ?>" value="<?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>" data-toggle="radio"><?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?></label>
                            <?php endforeach; ?>
                            <div class="login-form">
                                  <div class="form-group">
                                        <input name="key" type="password" class="form-control login-field" value="" placeholder="Wireless Password" id="login-pass" />
                                        <label class="login-field-icon fui-lock" for="login-pass"></label>
                                  </div>
                                  <a id="wan-submit" data-toggle="modal" data-target="#wanModal" class="btn btn-primary btn-lg btn-block" href="offline.html#">Connect</a>
                            </div>
                        </form>
                  </div>
            </div>
      </div>   
