<?php include ('setup_ap/js/setup_ap.pjs'); ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <?php
            echo _("
<h3>Setup</h3>
<p>Before you can use the NetAidKit, you've got to make it
your own. On this page, we will give your NetAidKit a new
wireless network name and password and choose an
administrator password you will use to make changes in
the future.</p>
<p>Let's get started!</p>
            ");
        ?>
    </div>
    <div class="col-xs-12 col-md-6">
        <?php $this->_displayMessages('ap'); ?>
        <?php include ('setup_ap/tiles/settings.phtml'); ?>
    </div>
</div>
