<?php include ('update/js/update.pjs'); ?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <img src="/img/logo/logo-nak-square.png">
        <h3>Update Required</h3>
        <p>A newer version of the software is available, please upgrade.</p>
        <p style="font-weight: bold">Warning: DO NOT turn off or disconnect the device during the upgrade process.</p>
        <form id="upgrade-form" action="/update/do_upgrade" method="POST">
            <a id="upgrade" type="button" class="btn btn-primary">Upgrade</a>
        </form>
        <div id="UpdateStatus" style="display:none">
            <h3 id="update_phase">Downloading update:</h3>
            <div class="progress">
                <div id="progressbar" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <span class="sr-only">10% Complete (success)</span>
                </div>
            </div>
        </div>
    </div>
</div>
