<?php $i=1; foreach ($this->_params['wifi_list'] as $ssid => $enctype): ?>
    <label class="radio">
        <input type="radio" name="ssid" id="optionsRadios<?= $i++; ?>" value="<?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>" data-toggle="radio"><?php if ($enctype <> 'Open'): ?><span class="fui-lock"></span><?php endif;?> <?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>
    </label>
<?php endforeach; ?>
