#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
    echo "starting netaidkit."
}

stop() {
    echo "stopping netaidkit."
}

boot() {
    # Check if uplink SSID is still in range. 
    ssid_conf=$(uci show wireless.@wifi-iface[0].ssid | grep -o "'.*'")
    ssid=${ssid_conf:1:$((${#ssid_conf} - 2))}
                                 
    in_range=$(/usr/bin/iwinfo wlan0 scan | grep $ssid)
    if [ -n "$in_range" ]; then            
        uci set wireless.@wifi-iface[0].disabled=0
        uci commit                         
        wifi                       
    else                                   
        uci set wireless.@wifi-iface[0].disabled=1      
        uci commit                                      
        wifi                                            
    fi                                                  
                                   
                                                        
    # Reboot daemons for state persistence.             
    stage=$(cat /etc/stage)                             
    if [ $stage = "3" ]; then              
        rm /var/log/tor/notices.log        
        /etc/init.d/tor start      
    elif [ $stage = "4" ]; then                         
        openvpn --daemon --config /nak/ovpn/current.ovpn
    fi                                                  
}  
