<div class="modal fade" id="restartModal" tabindex="-1" role="dialog" aria-labelledby="RestartLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><?php echo /* TRANSLATORS: window header */ _('The update is being installed'); ?></h4>
            </div>
            <div class="modal-body">
                <p>
                    <?php
                        $network = htmlspecialchars($this->_params['network'], ENT_QUOTES, 'UTF-8');
                        echo sprintf(_("
                        Please make sure you are still connected to either <b>%s</b> wireless network or
                        NetAidKit LAN port after the device restarts.
                        This page will refresh automatically."), $network);
                    ?>
                </p>
                <p id="sysupgrade-warning" class="sysupgrade-warning">
                <?php echo _("
                    Warning: DO NOT turn off or disconnect the device during the
                    install process!");
                ?>
                </p>
                <center><img src="/img/load.gif" /><br><br></center>
            </div>
        </div>
    </div>
</div>
