<div class="modal fade" id="apModal" tabindex="-1" role="dialog" aria-labelledby="apLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo _('Close'); ?></span></button>
                <h4 class="modal-title" id="apModalTitle"><?php echo _('Reset Access Point'); ?></h4>
            </div>
            <div class="modal-body">
                <p id="apModalText">
                    <?php
                        echo _("
You are about to reconfigure the NetAidKit Access Point.
You will be disconnected after clicking the 'Yes' button.
You can then reconnect with your new settings.</p>
                        ");
                    ?>
                <table>
                    <tr><td><?php echo _('New network name:'); ?></td> <td id="network-name" style="padding-left:10px" > ---</td></tr>
                    <!--<tr><td>Network password:</td> <td>---</td></tr>
                    <tr><td><?php echo _('Admin password:'); ?></td> <td>---</td></tr>
                    <tr><td><?php echo _('Distress password:'); ?></td> <td>---</td></tr>-->
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('No'); ?></button>
                <button id="ap-submit" href="/setup/ap" type="button" class="btn btn-primary"><?php echo _('Yes'); ?></button>
            </div>
        </div>
    </div>
</div>
