<?php include 'settings/modals/configure.phtml'; ?>

<div class="tile">
    <div class="login-form">
        <form action="/setup/ap" method="POST" id="ap-form">
            <?php $ssid_error = $this->_getFormError('ap', 'ssid'); ?>
            <?php $ssid_value = $this->_getFormValue('ap', 'ssid'); ?>
            <div class="form-group<?php if($ssid_error) echo ' has-error'; ?>">
                <input name="ssid" type="text" class="form-control login-field" value="<?php if(!$ssid_error) echo $ssid_value; ?>" placeholder="Enter a new network name" id="ssid"/>
                <label class="login-field-icon fui-loop" for="login-name"></label>
            </div>
            <div id="desc_ssid" class="collapse in">
                <div class="tile">
                    <p>Enter a new wireless network name for your NetAidKit. You will connect your devices to this wireless network once you completed setting up.</p>
                </div>
            </div>
            <?php $key_error = $this->_getFormError('ap', 'key'); ?>
            <?php $key_value = $this->_getFormValue('ap', 'key'); ?>
            <div class="form-group<?php if($key_error) echo ' has-error'; ?>">
                <input name="key" type="password" class="form-control login-field" value="<?php if(!$key_error) echo $key_value; ?>" placeholder="Enter a new network password" id="key"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_key" class="collapse in">
                <div class="tile">
                    <p>To make sure only you and people you trust can connect to your NetAidKit, choose a password to protect your new wireless network. The key must be between 8 and 64 characters long.</p>
                </div>
            </div>
            <?php $key_confirm_error = $this->_getFormError('ap', 'key_confirm'); ?>
            <?php $key_confirm_value = $this->_getFormValue('ap', 'key_confirm'); ?>
            <div class="form-group<?php if($key_confirm_error) echo ' has-error'; ?>">
                <input name="key_confirm" type="password" class="form-control login-field" value="<?php if(!$key_confirm_error) echo $key_confirm_value; ?>" placeholder="Confirm new network password" id="key_confirm"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_key_confirm" class="collapse in">
                <div class="tile">
                    <p>Please retype the new wireless network key.</p>
                </div>
            </div>
            <?php $adminpass_error = $this->_getFormError('ap', 'adminpass'); ?>
            <?php $adminpass_value = $this->_getFormValue('ap', 'adminpass'); ?>
            <div class="form-group<?php if($adminpass_error) echo ' has-error'; ?>">
                <input name="adminpass" type="password" class="form-control login-field" value="<?php if(!$adminpass_error) echo $adminpass_value; ?>" placeholder="Enter a new administrator password" id="adminpass"/>
                <label class="login-field-icon fui-user" for="login-pass"></label>
            </div>
            <div id="desc_adminpass" class="collapse in">
                <div class="tile">
                    <p>You will need a password to make changes to the configuration of the NetAidKit after setting up, choose one here. The password must be at least 8 characters long.</p>
                </div>
            </div>
            <?php $adminpass_confirm_error = $this->_getFormError('ap', 'adminpass_confirm'); ?>
            <?php $adminpass_confirm_value = $this->_getFormValue('ap', 'adminpass_confirm'); ?>
            <div class="form-group<?php if($adminpass_confirm_error) echo ' has-error'; ?>">
                <input name="adminpass_confirm" type="password" class="form-control login-field" value="<?php if(!$adminpass_confirm_error) echo $adminpass_confirm_value; ?>" placeholder="Confirm new administrator password" id="adminpass_confirm"/>
                <label class="login-field-icon fui-user" for="login-pass"></label>
            </div>
            <div id="desc_adminpass_confirm" class="collapse in">
                <div class="tile">
                    <p>Please retype the new admin password.</p>
                </div>
            </div>
            <!--<div class="form-group">
                <input name="distresspass" type="password" class="form-control login-field" value="" placeholder="Enter a distress password" id="distresspass" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_distresspass" class="collapse in">
                <div class="tile">
                    <p>If you plan on using the NetAidKit in repressive countries you can choose a distress password. Entering the distress password instead of your regular password will delete all information from the NetAidKit and make it present itself as a regular router.</p><p>If you do not think you will need it, you can just leave it empty.</p>
                </div>
            </div>-->
            <a id="finish-setup" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#apModal">Finish Setup</a>
        </form>
    </div>
</div>
