<div class="tile">
    <div class="login-form">
        <form action="/settings/password" method="POST" id="password-form">
            <?php $adminpass_check_error = $this->_getFormError('pwd', 'adminpass_check'); ?>
            <?php $adminpass_check_value = $this->_getFormValue('pwd', 'adminpass_check'); ?>
            <div class="form-group<?php if($adminpass_check_error) echo ' has-error'; ?>">
                <input name="adminpass_check" type="password" class="form-control login-field" value="<?php if(!$adminpass_check_error) echo $adminpass_check_value; ?>" placeholder="<?php echo _('Enter the current administrator password'); ?>" id="adminpass_check"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass_check" class="collapse in">
                <div class="tile">
                    <p>
                        <?php
                            echo _('
Please enter the current admininstrator password entered during configuration.
                        ');
                        ?>
                    </p>
                </div>
            </div>
            <?php $adminpass_error = $this->_getFormError('pwd', 'adminpass'); ?>
            <?php $adminpass_value = $this->_getFormValue('pwd', 'adminpass'); ?>
            <div class="form-group<?php if($adminpass_error) echo ' has-error'; ?>">
                <input name="adminpass" type="password" class="form-control login-field" value="<?php if(!$adminpass_error) echo $adminpass_value; ?>" placeholder="<?php echo _('Enter a new administrator password'); ?>" id="adminpass"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass" class="collapse in">
                <div class="tile">
                    <p>
                        <?php
                            echo _('
Enter a new administrator password used to log in to the configuration panel of the NetAidKit. The password must be at least 8 characters long.
                            ');
                        ?>
                    </p>
                </div>
            </div>
            <?php $adminpass_confirm_error = $this->_getFormError('pwd', 'adminpass_confirm'); ?>
            <?php $adminpass_confirm_value = $this->_getFormValue('pwd', 'adminpass_confirm'); ?>
            <div class="form-group<?php if($adminpass_confirm_error) echo ' has-error'; ?>">
                <input name="adminpass_confirm" type="password" class="form-control login-field" value="<?php if(!$adminpass_confirm_error) echo $adminpass_confirm_value; ?>" placeholder="<?php echo _('Confirm new administrator password'); ?>" id="adminpass_confirm" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass_confirm" class="collapse in">
                <p>
                    <div class="tile">
                        <?php echo _('Please retype the new administrator password.'); ?>
                    </div>
                </p>
            </div>
            <a id="submit-password" class="btn btn-primary btn-lg btn-block"><?php echo _('Change Password Settings'); ?></a>
        </form>
    </div>
</div>
