<div class="tile">
    <div class="login-form">
        <form action="/settings/password" method="POST" id="password-form">
            <div class="form-group">
                <input name="adminpass_check" type="password" class="form-control login-field" value="<?= $this->_getFormValue('pwd', 'adminpass_check'); ?>" placeholder="Enter the current administrator password" id="adminpass_check"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass_check" class="collapse in">
                <div class="tile">
                    <p>Please enter the current admininstrator password entered during configuration.</p>
                </div>
            </div>
            <div class="form-group">
                <input name="adminpass" type="password" class="form-control login-field" value="<?= $this->_getFormValue('pwd', 'adminpass'); ?>" placeholder="Enter a new administrator password" id="adminpass"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass" class="collapse in">
                <div class="tile">
                    <p>Enter a new administrator password used to log in to the configuration panel of the NetAidKit. The password must be at least 8 characters long.</p>
                </div>
            </div>
            <div class="form-group">
                <input name="adminpass_confirm" type="password" class="form-control login-field" value="<?= $this->_getFormValue('pwd', 'adminpass_confirm'); ?>" placeholder="Confirm new administrator password" id="adminpass_confirm" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_adminpass_confirm" class="collapse in">
                <div class="tile">
                    <p>Please retype the new administrator password.</p>
                </div>
            </div>
            <a id="submit-password" class="btn btn-primary btn-lg btn-block">Change Password Settings</a>
        </form>
    </div>
</div>
