<?php include 'wireless/modals/configure.phtml'; ?>

<div class="tile">
    <div class="login-form">
        <form action="/settings/ap" method="POST" id="ap-form">
            <?php $ssid_error = $this->_getFormError('ap', 'ssid'); ?>
            <?php $ssid_value = $this->_getFormValue('ap', 'ssid'); ?>
            <div class="form-group<?php if($ssid_error) echo ' has-error'; ?>">
                <input name="ssid" type="text" class="form-control login-field" value="<?php if(!$ssid_error) echo $ssid_value; ?>" placeholder="Enter a new network name" id="ssid"/>
                <label class="login-field-icon fui-loop" for="login-name"></label>
            </div>
            <div id="desc_ssid" class="collapse in">
                <div class="tile">
                    <p>Enter a new wireless network name for your NetAidKit. You will connect your devices to this wireless network.</p>
                </div>
            </div>
            <?php $key_error = $this->_getFormError('ap', 'key'); ?>
            <?php $key_value = $this->_getFormValue('ap', 'key'); ?>
            <div class="form-group<?php if($key_error) echo ' has-error'; ?>">
                <input name="key" type="password" class="form-control login-field" value="<?php if(!$key_error) echo $key_value; ?>" placeholder="Enter a new network password" id="key"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_key" class="collapse in">
                <div class="tile">
                    <p>To make sure only you and people you trust can connect to your NetAidKit, choose a password to protect your new wireless network. The key must be between 8 and 64 characters long.</p>
                </div>
            </div>
            <?php $key_confirm_error = $this->_getFormError('ap', 'key_confirm'); ?>
            <?php $key_confirm_value = $this->_getFormValue('ap', 'key_confirm'); ?>
            <div class="form-group<?php if($key_confirm_error) echo ' has-error'; ?>">
                <input name="key_confirm" type="password" class="form-control login-field" value="<?php if(!$key_confirm_error) echo $key_confirm_value; ?>" placeholder="Confirm new network password" id="key_confirm"/>
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <div id="desc_key_confirm" class="collapse in">
                <div class="tile">
                    <p>Please retype your wireless network key.</p>
                </div>
            </div>
            <input type="hidden" name="token" value="<?= $this->_getFormToken(); ?>" />
            <a id="submit-wireless" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#apModal">Change Wireless Settings</a>
        </form>
    </div>
</div>
