<div class="modal fade" id="wanModal" tabindex="-1" role="dialog" aria-labelledby="myWanLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php /* TRANSLATORS: as in, close window */ echo _('Close'); ?></span></button>
                <h4 class="modal-title" id="myModalLabel"><?php /* TRANSLATORS: window header/title */ echo _('Connecting'); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo _('Connecting...'); ?></p>
                <img src="/img/load.gif" />
            </div>
        </div>
    </div>
</div>
