<div class="tile">
    <?php echo _('<h3>Select a wireless network:</h3>'); ?>
    <form action="/setup/wan" method="POST" id="wan-form">
        <?php $i=1; foreach ($this->_params['wifi_list'] as $ssid => $enctype): ?>
            <label class="radio"><input type="radio" name="ssid" id="optionsRadios<?= $i++; ?>" value="<?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?>" data-toggle="radio"><?php if ($enctype <> 'Open'): ?><span class="fui-lock"></span><?php endif;?> <?= htmlspecialchars($ssid, ENT_QUOTES, 'UTF-8'); ?></label>
        <?php endforeach; ?>
        <div class="login-form">
            <div class="form-group">
                <input name="key" type="password" class="form-control login-field" value="" placeholder="Wireless Password" id="login-pass" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>
            <a id="wan-submit" data-toggle="modal" data-target="#wanModal" class="btn btn-primary btn-lg btn-block" href="offline.html#">
                <?php
                    /// TRANSLATORS: in the context of WiFi network selection
                    echo _('Connect');
                ?>
            </a>
        </div>
    </form>
</div>

<?php include ('wireless/modals/connecting.phtml'); ?>
