<div class="tile">
    <?php echo _('
<h3>VPN</h3>
<p>A Virtual Private Network creates an encrypted tunnel between the NetAidKit and a trusted network over the Internet.</p>
        ');
    ?>

    <form id="vpnform">
        <label class="radio">
            <input type="radio" name="optionsRadios" id="optionsRadios0" value="option0" data-toggle="radio" disabled />
            <a href="#" data-toggle="modal" data-target="#addVPN">
                <?php 
                    /// TRANSLATORS: button context
                    echo _('Add a VPN connection...');
                ?>
            </a>
        </label>

        <?php
            $checked = 'checked="checked"';
            foreach ($this->_params['vpn_options'] as $config) {
                $file = $config['file'];
        ?>

        <label class="radio"><input type="radio" <?= $checked?> name="optionsRadios" id="optionsRadios2" value="<?php echo $file ?>" data-toggle="radio"><?php echo $config['title']; ?> <a class="open-deleteVPN" data-toggle="modal" data-id="<?php echo $file ?>" href="#deleteVPN"  style="text-decoration: none;"><span class="fui-trash"></span></a> </label>

        <?php
            $checked = ''; /* Reset checked to empty for next items */ }
        ?>

        <a id="vpnConnectBtn" class="btn <?=($this->_params['cur_stage'] != STAGE_TOR && count($this->_params['vpn_options'])?'btn-primary':'btn-disabled')?> btn-lg btn-block" data-toggle="modal" <?=($this->_params['cur_stage'] != STAGE_TOR ? 'data-target="#vpnModal" href="online.html#"':'href=""');?>><?php echo _('Connect to VPN'); ?></a>
    </form>
</div>
